import { useState } from 'react'
import { Download } from 'lucide-react'
import { PageWrapper } from '@/components/layout/PageWrapper'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { payrollMonths, payrollYears } from '@/data/payroll'

export function MasterRoll() {
  const [year, setYear] = useState<string>(payrollYears[0])
  const [month, setMonth] = useState<string>('')
  const [submitting, setSubmitting] = useState(false)

  const generate = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!year || !month) return
    setSubmitting(true)
    // Backend will stream back a PDF — placeholder for now.
    setTimeout(() => {
      setSubmitting(false)
      window.alert(`Master roll for ${month} ${year} would be generated by Business Central.`)
    }, 600)
  }

  return (
    <PageWrapper title="Payroll Master Roll" description="Generate the consolidated payroll master roll report.">
      <form
        onSubmit={generate}
        className="portal-form-card mx-auto w-full max-w-2xl"
      >
        <div className="portal-form-card-header relative px-4 py-3 text-center text-sm font-semibold tracking-wide text-white sm:text-base">
          Generate Master Roll
        </div>
        <div className="space-y-4 p-4 sm:p-6">
          <div className="grid gap-3 sm:grid-cols-2 sm:gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="ceoYear">Year</Label>
              <Select
                id="ceoYear"
                value={year}
                onChange={(event) => setYear(event.target.value)}
                placeholder="Select year"
                options={payrollYears.map((y) => ({ value: y, label: y }))}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="ceoMonth">Month</Label>
              <Select
                id="ceoMonth"
                value={month}
                onChange={(event) => setMonth(event.target.value)}
                placeholder="Select month"
                options={payrollMonths.map((m) => ({ value: m, label: m }))}
              />
            </div>
          </div>
          <div className="flex justify-center pt-2">
            <Button type="submit" variant="accent" className="rounded-full" disabled={submitting || !month}>
              <Download className="h-4 w-4" />
              {submitting ? 'Generating…' : 'Generate report'}
            </Button>
          </div>
        </div>
      </form>
    </PageWrapper>
  )
}
